Fix #3
superMDguy/Variational-Recurrent-Autoencoder-Tensorflow pull request #4
Opened 2018-01-19 06:33 UTC by chanedwin

Enable use of single or multilayer LSTM/GRU for encoder and decoder

2018-01-21 02:47 UTC, superMDguy requested changes

2018-01-21 02:47 UTC, superMDguy commented on seq2seq_model.py
> +        cell = tf.contrib.rnn.BasicLSTMCell(size)
Can you name this variable something like `state` instead of `cell`, since it's not a single cell anymore?

2018-01-22 10:22 UTC, chanedwin commented
changed variable cell to state

2018-01-22 15:49 UTC, superMDguy commented
Ok, looks good now. Thanks!

2018-01-22 15:49 UTC, merged